[package]
authors.workspace = true
categories.workspace = true
description = "CDDA CD digital audio as per RedBook"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "redbook"
publish = false
readme = "README.md"
repository.workspace = true
rust-version = "1.95.0"
version = "0.0.1"

[features]
# for integration testing - expected results correlating to tests/assets
test_fixtures = []

[dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_Devices_Cdrom",
    "Win32_Storage",
    "Win32_Storage_FileSystem",
    "Win32_Security",
    "Win32_System",
    "Win32_System_IO",
] }
bytes.workspace = true
cdtoc.workspace = true
clap.workspace = true
exit_safely.workspace = true
flacenc.workspace = true
metaflac.workspace = true
musicbrainz_rs = { version = "0.13.0", git = "https://github.com/RustyNova016/musicbrainz_rs", features = [
    "sync",
    "native_tls",
] }
reqwest = { workspace = true, features = ["blocking", "native-tls", "json"] }
serde.workspace = true
serde_json.workspace = true
try_v2.workspace = true
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "json"] }
zune-jpeg.workspace = true

[dev-dependencies]
rstest.workspace = true

[build-dependencies]
build_safely.workspace = true
clap = { workspace = true, features = ["derive"] }
clap_builder.workspace = true
clap_complete.workspace = true
clap_mangen.workspace = true

[patch.crates-io]
api_bindium = { git = "https://github.com/RustyNova016/api_bindium" }
