name: Monthly stability checks

on:
  pull_request:
  push:
    paths:
      - ".github/workflows/rust-stability.yml"
  schedule:
    - cron: '0 3 6 * *'
  workflow_dispatch:
  workflow_call:

env:
    CARGO_TERM_COLOR: always

jobs:

  channels:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v6.0.2
    - name: install jaq
      uses: taiki-e/install-action@v2.79.14
      with:
        tool: jaq
    - name: process matrix
      id: matrix
      run: echo "matrix=$(jaq -c .channels .github/workflows/config/matrix.yml)" >> $GITHUB_OUTPUT
    - name: show outputs
      run: |
        echo "matrix: ${{ steps.matrix.outputs.matrix }}"
        cat .github/workflows/config/matrix.yml
        jaq -c .channels .github/workflows/config/matrix.yml

  test:
    needs:
      - channels
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.channels.outputs.matrix) }}
    env:
      RUSTC_BOOTSTRAP: ${{ matrix.bootstrap }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.2
    - name: update rust
      run: rustup update
    - name: Run tests
      run: cargo "+${{ matrix.channel }}" test --no-fail-fast

  lint:
    needs:
      - channels
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.channels.outputs.matrix) }}
    env:
      RUSTC_BOOTSTRAP: ${{ matrix.bootstrap }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.2
    - name: update rust
      run: rustup update && rustup component add --toolchain ${{ matrix.channel }} clippy
    - name: clippy
      run: cargo +${{ matrix.channel }} clippy -- --deny warnings

  report:
    permissions:
      contents: read
      issues: write
    if: ${{ always() }}
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.2
    - name: Create issue on failure
      if: ${{ github.event_name != 'pull_request' && (needs.test.result == 'failure' || needs.lint.result == 'failure') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue create --title "Monthly tests failed" --body "Run ID: $GITHUB_RUN_ID" --assignee "MusicalNinjaDad"
